name: Generate RSS HTML

on:
  schedule:
    - cron: "0 6 * * *"  # každý den v 6:00 ráno UTC (8:00 v ČR)
  workflow_dispatch:      # umožní ruční spuštění

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser

      - name: Generate HTML from RSS
        run: python rss_to_html.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: false
